version: '2.3'
services:
    betterfps:
        image: gradle:4.10.0-jdk8-slim
        user: "1002:1002"
        environment:
          - GIT_COMMIT=${GIT_COMMIT:-latest}
          - BETTERFPS_DEBUG=1
        volumes:
            - ./:/root
            - ./.gradle:/root/.gradle
        working_dir: /root
        entrypoint: gradle
